repo: https://github.com/openwrt/openwrt.git
branch: v22.03.4
git_clone_dir: openwrt-22.03/openwrt-22.03.4
openwrt_root_dir: openwrt-22.03/openwrt-22.03.4
revision: 94adc23fa693d1b129ce1718573dfb12594f20f8

patch_folders:
  - patches-22.03.4/
